"""Phase 9: api_keys table

Revision ID: b9273a98ca4c
Revises: 85a67264382e
Create Date: 2026-02-27 03:02:57.949147
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9273a98ca4c'
down_revision: Union[str, None] = '85a67264382e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), server_default='{all}', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_keys_org', 'api_keys', ['org_id'], unique=False)
    op.create_index('idx_api_keys_prefix', 'api_keys', ['prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_api_keys_prefix', table_name='api_keys')
    op.drop_index('idx_api_keys_org', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
