"""Phase 10: add config column to teams

Revision ID: d29768ed705e
Revises: 8fd38d37a5f3
Create Date: 2026-02-27 03:10:35.935674
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd29768ed705e'
down_revision: Union[str, None] = '8fd38d37a5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'config')
    # ### end Alembic commands ###
